In [1]:
# Q1 - create a list and convert into numpy and print it?

import numpy as np
list = [1,2,3,4,5]
np.array(list)

array([1, 2, 3, 4, 5])

In [2]:
# Q2- make a 3x3 matrix , convert in into numpy array and then print it?
matrix = [[1,2,3],[4,5,6],[7,8,9]]
np.array(matrix)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [35]:
# Q3 - make a 3x3 matrix using arange,reshape?
arr = []
for i in range(1,18):
    if(i%2!=0):
       arr.append(i) # all i values is converted into list (name of list is arr)
arr2=np.array(arr) # arr2 list is converted into array
matrix1 = arr2.reshape(3,3)
matrix1





array([[ 1,  3,  5],
       [ 7,  9, 11],
       [13, 15, 17]])

In [67]:
# Q4- Create numpy array with 10 random no's from 0 to 10(one no should be greater than 1)?
rand_nums = np.random.randint(0,10,10)
rand_nums




array([6, 9, 9, 8, 5, 9, 7, 7, 8, 0])

In [73]:
# Q5 - create a numpy array, convert it into 2d array with 5 rows and print it?
arr5 = np.array([1,2,3,4,5])
arr5.reshape(5,1)

array([[1],
       [2],
       [3],
       [4],
       [5]])

In [75]:
# Q6- PRINT SHAPE OF THE ABOVE CURATED ARRAY?
arr5.shape

(5,)

In [83]:
# Q7- Create a numpy array with 10 elements in it. Access the 3rd,4th,9th element?
arr6 = np.array([1,2,3,4,5,6,7,8,9,10])
print(arr6[2],arr6[3],arr6[8])


3 4 9


In [96]:
# Q8- Print alternate elements of above array?
print(arr6[0:2],arr6[4:8],arr6[9])



[1 2] [5 6 7 8] 10


In [98]:
# Q9- Change the last 3 elements into 100?
arr6[7:len(arr6)] = 100
arr6

array([  1,   2,   3,   4,   5,   6,   7, 100, 100, 100])

In [110]:
# Q10- Create a 5x5 matrix ,print it. Then print the middle (3x3) matrix?
array = np.arange(25)
matrix5=array.reshape(5,5)
matrix5

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [111]:
# now printing the middle (3x3) matrix
matrix5[1:4,1:4]

array([[ 6,  7,  8],
       [11, 12, 13],
       [16, 17, 18]])